name: CI
on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: borales/actions-yarn@v4

            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            - name: Run lint
              uses: borales/actions-yarn@v4
              with:
                  cmd: lint

            - name: Run build
              uses: borales/actions-yarn@v4
              with:
                  cmd: build
